version: "3.8"

services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: ./docker/front_dev/Dockerfile
  #   ports:
  #     - 8000:8000

  mongo_db:
    image: mongo
    ports:
      - 27017:27017
    logging:
      driver: none

  redis_db:
    image: redis
    ports:
      - 6379:6379
    logging:
      driver: none
    environment:
      - TZ=Asia/Seoul

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
