from .devSocket import router as devRouter
from .image import router as imageRouter
from .nation import router as nationRouter
from .manufacturer import router as manufacturerRouter
from .car import router as carRouter
from .data import router as dataRouter
from .tag import router as tagRouter
from .indexedDB import router as indexedDBRouter
from .tagkind import router as tagKindRouter
from .fh5 import router as FH5Router
from .auth import router as AuthRouter
from .dev import router as devRouter
from .user import router as userRouter
from .comment import router as commentRouter
